CREATE TABLE ACCOUNT (
    ACCOUNT_ID    BIGINT           NOT NULL PRIMARY KEY,
    CRT_CLASS     TEXT             NOT NULL,
    CUSTOMER_ID   BIGINT           NOT NULL,
    ACCT_TYPE     CHAR(3)          NOT NULL,
    ACCT_NUMBER   INT              NOT NULL,
    BALANCE       DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    LUID          CHAR(15)         NOT NULL,
    LUTS          BIGINT           NOT NULL);

CREATE UNIQUE INDEX ACCT_NUM_IDX ON ACCOUNT (ACCT_NUMBER);

CREATE UNIQUE INDEX ACCOUNT_IDX ON ACCOUNT (ACCOUNT_ID, LUID, LUTS);

CREATE TABLE CUSTOMER (
    CUSTOMER_ID     BIGINT          NOT NULL PRIMARY KEY,
    CRT_CLASS       TEXT            NOT NULL,
    FIRST_NAME      VARCHAR(40)     NOT NULL,
    LAST_NAME       VARCHAR(40)     NOT NULL,
    SOCIAL_SECURITY CHAR(11)        NOT NULL,
    LUID            CHAR(15)        NOT NULL,
    LUTS            BIGINT          NOT NULL);

CREATE UNIQUE INDEX CUSTOMER_IDX ON CUSTOMER (CUSTOMER_ID, LUID, LUTS);

CREATE TABLE ORA_SEQGEN (
    NAME           VARCHAR(25)     NOT NULL PRIMARY KEY,
    NEXT_SEQ       BIGINT          NOT NULL DEFAULT 1,
    LUTS           BIGINT          NOT NULL);

CREATE UNIQUE INDEX SEQGEN_IDX ON ORA_SEQGEN (NAME, LUTS);

INSERT INTO ORA_SEQGEN (NAME, NEXT_SEQ, LUTS)
VALUES ('node', 1, 0);

INSERT INTO ORA_SEQGEN (NAME, NEXT_SEQ, LUTS)
VALUES ('ACCT_NUM', 10000, 0);

CREATE TABLE LWP_USER (
    USER_ID       VARCHAR(25)     NOT NULL PRIMARY KEY,
    PASSWORD      VARCHAR(25)     NOT NULL);

INSERT INTO LWP_USER (USER_ID, PASSWORD)
VALUES ('oreilly', 'oreilly');