imaginary.lwp.persist.driver=org.dasein.soul.Driver
imaginary.lwp.jdbcURL=jdbc:postgresql://172.21.32.1:5432/bank
imaginary.lwp.user=postgres
imaginary.lwp.password=postgres
imaginary.lwp.objectServer=rmi://localhost:1099/ObjectServer
imaginary.lwp.xaction=com.imaginary.lwp.jdbc.JDBCTransactionImpl
imaginary.lwp.handler.com.imaginary.bank.CustomerEntity=com.imaginary.bank.CustomerPersistence
imaginary.lwp.handler.com.imaginary.bank.AccountEntity=com.imaginary.bank.AccountPersistence
